// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ0k7aB-JeMcZlHfoMnrm122TNMuDxbj8',
    appId: '1:357487132955:web:45e1a7972cb94690f053be',
    messagingSenderId: '357487132955',
    projectId: 'project-6813252486676903306',
    authDomain: 'project-6813252486676903306.firebaseapp.com',
    storageBucket: 'project-6813252486676903306.appspot.com',
    measurementId: 'G-HXW5MX7HTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWN58QM4VoZZs7X0_e2ETdqMS1NFBIdbo',
    appId: '1:357487132955:android:62ea5124f5f9f4f5f053be',
    messagingSenderId: '357487132955',
    projectId: 'project-6813252486676903306',
    storageBucket: 'project-6813252486676903306.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDALDxwf-Fp4NDD96D2-JZ5oHL23vPpiyI',
    appId: '1:357487132955:ios:c67ac5469bd929c4f053be',
    messagingSenderId: '357487132955',
    projectId: 'project-6813252486676903306',
    storageBucket: 'project-6813252486676903306.appspot.com',
    iosClientId: '357487132955-5fie78fvemfchfc3iukcf842u09p9v4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDALDxwf-Fp4NDD96D2-JZ5oHL23vPpiyI',
    appId: '1:357487132955:ios:c67ac5469bd929c4f053be',
    messagingSenderId: '357487132955',
    projectId: 'project-6813252486676903306',
    storageBucket: 'project-6813252486676903306.appspot.com',
    iosClientId: '357487132955-5fie78fvemfchfc3iukcf842u09p9v4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
